FROM python:3.12-rc-slim-bullseye

WORKDIR /code

RUN apt-get -y update
RUN apt-get -y upgrade

COPY ./requirements.txt /code/requirements.txt
COPY ./.env /code/.env
RUN pip install pip --upgrade
RUN pip install -r /code/requirements.txt
