version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
  
  db:
    container_name: db
    image: postgres:15-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=project
    ports:
      - "5432:5432"

